services:
  nginx:
    image: nginx:alpine
    ports: 
      - 5173:80
    volumes:
      - ./nginx/:/usr/share/nginx/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - web
      - app

  db:
    image: postgres:16-alpine
    container_name: supynes-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-supynes}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: supynes-api
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/supynes?sslmode=disable}
      PORT: ${PORT:-8085}
      JWT_SECRET: ${JWT_SECRET:-supsersruipr421421!surusp_rjsdrjds}
    depends_on:
      - db

  web:
    image: node:20-alpine
    working_dir: /web
    command: sh -c "npm i && npm run dev -- --host"
    volumes:
      - ./web:/web
    depends_on: [ app ]

volumes:
  pgdata:
