name: Pull updates to prod

on: [push]

jobs:
  pull-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Pull
        run: sudo git pull
        working-directory: /home/rokas/repos/supynes
      - name: Rebuild
        run: sudo docker compose up -d --build
        working-directory: /home/rokas/repos/supynes
